spring:
  mail:
    host: smtp.qq.com
    username: 2715310362@qq.com
    password: jfivzapmzwqkdfbh
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true

management:
  server:
    port: 9001   #actuator端口
  endpoint:
    web:
      exposure:
         include: '*'
    health:
      show-details: always   #显示健康具体信息  默认不会显示详细信息

#定义info信息
#info:
#  app.name: mySpringboot
#  app.version: v1.0.0
#  company.name: www.cblue.com
